package at.ac.fhsalzburg.mmtlb.applications;

public enum ImageModificationType {

	CONTRAST_STRETCHING, //
	GAMMA_CORRECTION, //
	HISTOGRAM_EQUALIZATION, //
	AVERAGING_FILTER, //
	MEDIAN_FILTER, //
	LAPLACIAN_FILTER, //
	SOBEL_FILTER, //
	HIGHBOOST_FILTER, //
	GLOBAL_THRESHOLDING, //
	ITERATIVE_THRESHOLDING, //
	OTSU_THRESHOLDING;

}
